### Monday Summary
POST localhost:8080/api/v1/basic/summary
Content-Type: application/json

{
  "foodOnAmount" : [
    {
      "first": "Отбивные курица ананас",
      "second": 1
    },
    {
      "first": "Протеиновый шейк",
      "second": 0.5
    },
    {
      "first": "Омлет с сыром",
      "second": 1
    },
    {
      "first": "Гречка с молоком",
      "second": 0.5
    }
  ]
}

### GET exact dish
GET localhost:8080/api/v1/basic/Овсяная Каша с Шоколадом
Accept: application/json