### GET request with a header
GET localhost:8080/api/v1/basic
Accept: application/json

### GET request with a header
GET localhost:8080/api/v1/basic/recalculate
Accept: application/json

### GET request with a header
GET localhost:8080/api/v1/basic/Десерт Банановая Овсянка
Accept: application/json

### POST
POST localhost:8080/api/v1/basic/create
Content-Type: application/json

{
  "name": "Десерт Банановая Овсянка",
  "type": 2,
  "ingredients" : [
    {
      "name": "Овсянка",
      "weight": 50
    },
    {
      "name": "Банан",
      "weight": 220
    },
    {
      "name": "Протеин",
      "weight": 55
    },
    {
      "name": "Йогурт",
      "weight": 120
    },
    {
      "name": "Яйцо",
      "weight": 115
    }
  ]
}

### POST
POST localhost:8080/api/v1/basic/summary
Content-Type: application/json

{
  "foodOnAmount" : [
    {
      "first": "Тако с курицей овощами и сыром",
      "second": 1
    },
    {
      "first": "Овсяная Каша с Шоколадом",
      "second": 1
    }
  ]
}